language: cpp

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt update -qq
  - sudo apt install -y g++-8
  - sudo apt install -y libgmp-dev
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - eval "${MATRIX_EVAL}"
addons:
  apt:
    update: true
install:
  - mkdir build
  - cd build
  - cmake ..
  - make
compiler:
  - g++-8
script:
  - ./cvm ../test.cms
